Données : suppressions et mises à jour de bulk messages
demarches-simplifiees/demarches-simplifiees.fr pull request #10071
Opened 2024-03-05 16:19 UTC by E-L-T

2024-03-10 16:58 UTC, mfo requested changes
Ça aurait pu se cranter par des requetes SQL, mais le volume etant petit, je préfère cette approche de filter plutot qu'une requete SQL aui rajoute de la complexité ! juste il manque un `.all`

2024-03-10 16:58 UTC, mfo commented on app/tasks/maintenance/backfill_bulk_messages_with_procedure_id_task.rb
> +      BulkMessage.filter { |bm| bm.procedure.nil? && bm.groupe_instructeurs.present? }
```suggestion
      BulkMessage.all.filter { |bm| bm.procedure.nil? && bm.groupe_instructeurs.present? }
```

2024-03-10 16:58 UTC, mfo commented on app/tasks/maintenance/backfill_bulk_messages_with_procedure_id_task.rb
> +    end
```suggestion
```

pas necessaire

2024-03-10 16:58 UTC, mfo commented on app/tasks/maintenance/destroy_incomplete_bulk_messages_task.rb
> +      BulkMessage.filter { |bm| bm.procedure.nil? && bm.groupe_instructeurs.blank? }
```suggestion
      BulkMessage.all.filter { |bm| bm.procedure.nil? && bm.groupe_instructeurs.blank? }
```

2024-03-11 08:29 UTC, E-L-T commented
> Ça aurait pu se cranter par des requetes SQL, mais le volume etant petit, je préfère cette approche de filter plutot qu'une requete SQL aui rajoute de la complexité ! juste il manque un `.all`

woops, merci ! C'est fait

2024-03-11 17:42 UTC, merged