chore(js): update coldwired, react and combobox
demarches-simplifiees/demarches-simplifiees.fr pull request #10404
Opened 2024-05-06 16:12 UTC by tchak

2024-05-22 06:22 UTC, mfo reviewed
quelques commentaires en vue de la relecture

2024-05-22 06:22 UTC, mfo commented on app/javascript/components/ComboBox.tsx
> +}
une idée pour faciliter la relecture, j'imagine qu'on peut faire une pause sur ce fichier ici (ou isoler un commit), la suite étant de voir l'implem complete via rails (concrètement, voir l'usage d'un `SingleCombobox` avant de voir l'implem des autres variantes).

2024-05-22 06:22 UTC, mfo commented on app/javascript/components/ComboBox.tsx
> +}
après avoir vu l'usage d'un `SingleCombobox`, on peut revenir ici (voir isoler un commit avec ces changements) afin de voir l'implem react du `MultiComboBox`, puis voir l'implem via rails d'un `MultiComboBox`

2024-05-22 06:22 UTC, mfo commented on app/javascript/components/ComboBox.tsx
> +}
après avoir vu l'usage d'un `MultiComboBox`, on peut revenir ici (voir isoler un commit avec ces changements) afin de voir l'implem react du `RemoteComboBox`, puis voir l'implem via rails d'un `RemoteComboBox`

2024-05-22 06:22 UTC, mfo commented on app/controllers/data_sources/education_controller.rb
> +class DataSources::EducationController < ApplicationController
trop bien d'aligner ce champs comme les autres dans le ns datasources!

2024-05-22 06:22 UTC, mfo commented on app/controllers/administrateurs/experts_procedures_controller.rb
> +      emails = emails.map(&:strip).map(&:downcase)
bien plus propre ainsi tx !

2024-05-22 07:23 UTC, tchak commented on app/javascript/components/ComboBox.tsx
> +        <Input className="fr-select fr-autocomplete" ref={inputRef} />
oui

2024-05-22 07:23 UTC, tchak commented on app/javascript/components/ComboBox.tsx
> +      {label ? <Label className="fr-label">{label}</Label> : null}
c'est géré par react-aria

2024-05-22 07:55 UTC, mfo commented on app/javascript/components/ComboBox.tsx
> +        <Input className="fr-select fr-autocomplete" ref={inputRef} />
totalement magique cette histoire :D

2024-06-11 15:49 UTC, mfo requested changes
[0001-fix-combobox-admin-procedures-73682-groupe_instructe.patch](https://github.com/user-attachments/files/15791654/0001-fix-combobox-admin-procedures-73682-groupe_instructe.patch)

attention, on a un bug qui peut donner une boucle infini , ne pouvant pas pusher directement je te propose un patch (j'imagine que tu feras mieux)

2024-06-24 13:49 UTC, colinux commented
J'ai retesté le flaky test en brouillon sur cette branche. Il reste mais on dirait qu'il prend une autre forme (ou alors ça en est un tout autre mais ce serait étrange) : 

Capybara::ElementNotFound:
       Unable to find css ".fr-menu__item"

De ce que j'avais commencé à cerner sur `main`, on aurait pu essayer d'attendre le next tick  pour déclencher l'autosave, car le hidden field n'avait pas nécessairement déjà sa value  (surtout si on tape vite et que l'autocomplete n'a encore pas  remonté de résultat pré-sélectionné). Dans cette branche, je ne sais pas quel serait le fix équivalent.

2024-07-03 12:27 UTC, mfo approved these changes

2024-07-05 12:04 UTC, merged