ETQ usager : j'accède au bouton JDMA depuis la page Merci et depuis le mail de dépôt de dossier
demarches-simplifiees/demarches-simplifiees.fr pull request #10502
Opened 2024-06-07 16:40 UTC by Benoit-MINT

En réponse à l'issue https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10118 : 

![Capture d’écran 2024-06-07 à 18 18 19](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/72251526/b1f69325-ae5f-4d81-a776-3bc9cd2e92ff)

![Capture d’écran 2024-06-07 à 18 17 24](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/72251526/99bd2e8e-bc48-47de-b031-4014e05796bd)

Concernant l'apparition dans le mail :
- pour une démarche non déclarative, au mail de dépôt uniquement ;
- pour une démarche auto-instruction, au mail de dépôt uniquement (pas dans le mail qui suit sur passage en instruction) ;
- pour une démarche auto-acceptée, jamais afin d'éviter un éventuel doublon avec Services Publics +

2024-06-11 07:54 UTC, colinux requested changes
En plus des petits feedbacks ci-dessous, je ne vois pas bien ce qui vérifie cette condition évoquée dans ta PR :  _pour une démarche auto-instruction, au mail de dépôt uniquement_ (à moins que l'email  en construction soit quand même envoyé ? ça me paraît étrange)

2024-06-11 07:54 UTC, colinux commented on app/mailers/notification_mailer.rb
> +    return unless params[:state] == Dossier.states.fetch(:en_construction) && @dossier.procedure.monavis_embed
plusieurs personnes dans l'équipe ne sont pas fan d`unless`( c'est pas mon cas) , mais alors s'il y a une double condition, je les rejoins c'est vraiment un `if` qu'il faut :)

Par exemple : 
```
# ça passerait pour moi, (pas pour tous) : 
return unless params[:state] == Dossier.states.fetch(:en_construction)

# mais avec une condition plus compliquée , ou une négation, c'est piégeux on veut l'équivalent en if
```

2024-06-11 16:00 UTC, Benoit-MINT commented on app/mailers/notification_mailer.rb
> +    return unless params[:state] == Dossier.states.fetch(:en_construction) && @dossier.procedure.monavis_embed
done

2024-06-11 16:01 UTC, Benoit-MINT commented on .DS_Store
done

2024-06-11 16:04 UTC, Benoit-MINT commented
> En plus des petits feedbacks ci-dessous, je ne vois pas bien ce qui vérifie cette condition évoquée dans ta PR : _pour une démarche auto-instruction, au mail de dépôt uniquement_ (à moins que l'email en construction soit quand même envoyé ? ça me paraît étrange)

C'est bien exact, pour une démarche en auto-instruction, il y a bien 2 mails envoyés successivement, (i) dépôt/construction et (ii) instruction. J'étais parti du principe que c'était un comportement voulu d'où la "simple" logique utilisée dans ce cas qui évite donc l'effet de doublon.

2024-06-14 11:39 UTC, colinux approved these changes
dernier ajustement et je te laisse merger ;)

2024-06-14 11:39 UTC, colinux commented on app/mailers/notification_mailer.rb
> +
je vais tatillonner encore un peu, mais surtout dans le cadre de ta montée en compétences :) 
Le `else … return` est inutile : on ne renvoie rien et de toute façon ruby renvoie tjs la dernière expression évaluée. (C'est à dire que si on ne rentre pas dans le `if`, la dernière expression serait `nil`, même sans expliciter le  `else`.). C'est pour ça qu'on voit peu de return en ruby, ils sont surtout là pour sortir d 'une méthode et ne plus exécuter la suite). 

Donc ici cela pourrait se simplifier en : 
```suggestion
  def set_jdma
    if params[:state] == Dossier.states.fetch(:en_construction) && @dossier.procedure.monavis_embed
      @jdma_html = @dossier.procedure.monavis_embed_html_source("email")
    end
  end
```

Une autre version pourrait être : (pas forcément plus claire ici à cause du !=, mais si ça avait été == ça aurait été très bien).

```ruby
  def set_jdma
    return if params[:state] != Dossier.states.fetch(:en_construction)
    return if @dossier.procedure.monavis_embed.blank?

    @jdma_html = @dossier.procedure.monavis_embed_html_source("email")
  end
```

A noter qu'en variante avec unless personnellement je trouve que c'est assez lisible aussi  : 

```ruby
  def set_jdma
    return unless params[:state] == Dossier.states.fetch(:en_construction)
    return unless @dossier.procedure.monavis_embed.present? 

    @jdma_html = @dossier.procedure.monavis_embed_html_source("email")
  end
```

2024-06-14 16:38 UTC, merged