ETQ usager: je ne peux ajouter qu'une unique PJ pour les anciennes procédures qui l'exigent
demarches-simplifiees/demarches-simplifiees.fr pull request #10511
Opened 2024-06-11 13:10 UTC by Benoit-MINT

En réponse à l'issue https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/10186

Ceci concerne donc que les anciennes démarches où l'admin pouvait indiquer si une ou plusieurs PJ étaient autorisées.

Le pb venait de l'association entre le for dans la balise du label et l'id de l'input associé, qui rendait donc cliquable le label, permettant ainsi à l'usager de sélectionner une nouvelle PJ.

La modification proposée introduit une exception pour le type de champ PJ et lorsque les PJ multiples ne sont pas autorisées, avec pour conséquence de ne plus forcer la valeur de l'attribut for.

2024-06-14 08:10 UTC, colinux commented
Enlever l'attribut `for`, ça ne va pas le faire niveau accessibilité. Et l'importance de l'accessibilité est supérieure à l'impact de ce bug (on a eu qu'une remontée ou 2), sachant que ça ne concerne que d'anciennes démarches (publiées avant décembre 2022). Donc à moins de trouver une autre façon de le corriger (et pour pas trop "cher" vu le faible enjeu), je préfère que ça reste comme c'est

2024-06-27 15:00 UTC, Benoit-MINT commented
L'autre logique proposée pour ne pas dégrader l'accessibilité est de jouer avec un attribut "disabled" sur l'input.

Pour info ici, contrairement à mon premier commentaire, ce bug se retrouve également pour les démarches actuelles (PJ multiples), en permettant d'insérer plus de 10 PJ (nb fixé arbitrairement dans le code).

2024-07-01 11:27 UTC, colinux requested changes
déso je vois encore un point bloquant, cf commentaire. Dispo si nécessaire

2024-07-01 11:27 UTC, colinux commented on app/controllers/attachments_controller.rb
> +    @champ = Champ.find(params[:champ]) if params[:champ]
J'ai l'impression que ça pose un pb de sécu car on render directement le champ à partir de son id. C'est à dire que si j'injecte un champ id au hasard et qu'il existe, on verra les attachments déjà mis car on controlle pas que le champ appartient à l'user.

Là à chaud je me dis que dans le destroy path, on pourrait passer un couple dossier_id/champ stable_id 
et un peu comme ce qui est fait dans `app/controllers/champs/champ_controller.rb#find_champ` : le policy scope sur le dossier s'assure que l'user a le droit de voir le dossier, et on récupère un champ par son stable id appartenant à ce dossier. A voir aussi le cas dans un bloc répétable, il doit falloir aussi passer le row_id lorsque c'est présent.
Donc pour résumer: le champ s'identifie avec dossier_id + champ stable_id + row_id le cas échéant.

2024-07-08 13:52 UTC, colinux approved these changes

2024-07-08 14:37 UTC, merged