ETQ Usager se connectant par FC, je dois confirmer mon mail
demarches-simplifiees/demarches-simplifiees.fr pull request #10570
Opened 2024-07-01 14:41 UTC by kara22

2024-07-10 09:08 UTC, kara22 commented
L'ajout de correcteur de typo sera fait dans une autre PR

2024-07-10 13:47 UTC, LeSim reviewed
Première passe avec en plus :
- tu veux pas nous remettre au DS FR la page de fusion ?
![Screenshot 2024-07-10 at 15-37-06 Fusion des comptes FC et demarches-simplifiees fr · demarches-simplifiees fr](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/907405/363b61e0-a755-4e6f-87cd-38178f59c687)
- dans `mail_merge_with_existing_account`, il faudrait que update `email_verified_at`
- lorsque l'utilisateur est non rattache a fci mais que son mails est déjà utilisé, qu'il en choisi un autre, il faudrait qu'il soit prévenu qu'il doit valider son mail.


ca fait beaucoup, mais c'est parce que ta pr est lisible :)

2024-07-10 13:47 UTC, LeSim commented on config/locales/fr.yml
> +        click_the_link_in_the_email: Veuillez cliquer sur le lien du mail pour confirmer votre compte et vous connecter avec France Connect pour les prochaines fois.
```suggestion
        click_the_link_in_the_email: Vous devez impérativement cliquer sur le lien du mail pour activer votre adresse et recevoir les notifications sur l'avancement de vos dossiers.
```

2024-07-10 13:47 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  end
J'ai du mal a comprendre comment ça peut marcher : l'utilisateur est redirigé la par exemple depuis la `confim_email` et il n'est pas forcément loggué, du coup `@user` est nil

2024-07-10 13:47 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +      redirect_to root_path(user), notice: "Votre lien a expiré. Demandez un nouveau lien en cliquant sur le bouton ci-dessous"
heu je suis pas sur du texte du coup, on est pas dans le cas ou un lien a été renvoyé ?

2024-07-10 13:47 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  def connect_france_connect_particulier_redirect
j'ai l'impression que cette methode n'est pas utilisée

2024-07-10 13:47 UTC, LeSim commented on app/models/user.rb
> -    update!(email_verified_at: Time.zone.now)
yes !

2024-07-10 13:47 UTC, LeSim commented on app/views/user_mailer/custom_confirmation_instructions.html.haml
> +- content_for(:title, 'Confirmez votre email')
On pourrait reprendre des idée du mail de merge :
![Screenshot 2024-07-10 at 15-33-41 LetterOpenerWeb](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/907405/a2b08b1e-86f7-4241-b665-ed3176e73874)

- mettre le lien en plus du bouton
- dire la durée de validité du lien
- que faire si on est pas a l'origine de la demande et l'adresse de contact

2024-07-11 13:24 UTC, kara22 commented on app/controllers/france_connect/particulier_controller.rb
> +  def connect_france_connect_particulier_redirect
si elle permet la redirection lorsqu'on clique sur "continuer" une fois qu'on a l'alerte qu'on doit confirmer son mail

2024-07-11 13:49 UTC, kara22 commented on app/controllers/france_connect/particulier_controller.rb
> +      redirect_to root_path(user), notice: "Votre lien a expiré. Demandez un nouveau lien en cliquant sur le bouton ci-dessous"
On est dans le cas où le lien est expiré et qu'il doit cliquer sur le bouton dans l'interface pour renvoyer un lien.

2024-07-16 12:22 UTC, LeSim requested changes
il y a une faille de type `connect(User.find(params[:user_id]))` à fixer

2024-07-16 12:22 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  end
```suggestion
  def use_fc_email? = cast_bool(params[:use_france_connect_email])
```

2024-07-16 12:22 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +    user = User.find(params[:user_id])
:warning: :skull: le code introduis une faille de sécurité, tu peux te connecter avec le compte de n'importe qui

2024-07-16 12:22 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  end
Je pense que tu as ici un pb pour trouver le `@user`.

Admettons :
- l'utilisateur se connecte pour la 1er fois par FC
- on envoie un lien de confirmation
- il clique sur le lien 5 jours plus tard (il n est plus connecté), `confirm_email` redirige vers `resend_confirmation`
- le before action `set_user` ne retrouve pas l'utilisateur (non connecté) (ou prend n'importe lequel il y a dans `params[:email]` : injection possible ?)
- du coup, je suis redirigé vers la home

J'ai l'impression que tu devrais plutot utiliser le confirmation_token

2024-07-22 14:20 UTC, LeSim reviewed
courage ...

2024-07-22 14:20 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +      return
```suggestion
```

2024-07-22 14:20 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  def set_user
```suggestion
  def set_user_by_confirmation_token
```

2024-07-22 14:20 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  before_action :authenticate_user!, only: [:confirm_email, :resend_confirmation]
```suggestion
  ```

je ne comprends pas ce before_action.

Ca voudrait dire que t'es obligé de t'authentifier pour confirmer son compte. Il me semble que la facon standard de faire est de retrouver l'utilisateur à partir de son confirmation_token.

Je me demande si tu n'as pas oublié cette ligne vu que tu mets les 2 methodes dans `set_user` que je te propose de renommer en `set_user_by_confirmation_token`

2024-07-22 14:20 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  def connect_france_connect_particulier_redirect
Est ce que cette méthode est toujours utilisé ? peux-tu me montrer le code qui y fait référence ?
si ce n'est pas le cas peux tu la supprimer, ansi que ca route, et dans le before_action set_user ?

2024-07-22 14:34 UTC, LeSim commented on app/models/france_connect_information.rb
> +      user = User.find_by(email: email.downcase)
pourquoi ?

```suggestion
```

2024-07-22 14:34 UTC, LeSim commented on app/models/france_connect_information.rb
> +      send_custom_confirmation_instructions(user)
```suggestion
```

Il me semble que tu l'envoies 2 fois dans la ligne 116 de `particulier_controller`.
Du coup de supprimer l'appel ici, et de rajouter un appel explicite ligne 63 de `particulier_controller`

2024-07-22 14:34 UTC, LeSim commented on config/routes.rb
> +    get 'particulier/email_field', to: 'particulier#email_field', as: :turbo_frame_email_field
```suggestion
```

2024-07-23 08:40 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +    end
Je te propose de supprimer la gestion d'erreur ici, car
- elle n'est pas utilisé non plus ligne 112
- il ne devrait pas y avoir d'erreur de validation car pas d'input user
- du coup, on allège le controller, et c'est pas mal :)


par ailleurs, je te propose ces modifs pour supprimer le merge_token maintenant qu'on en a plus besoin.

```suggestion
    @fci.associate_user!(email)
    # l'association est faites, on a plus besoin du token
    @fci.delete_merge_token!
    # on sign in au plus tot car on a plus de token
    sign_out :user if user_sign_in?
    sign_in user
    # on recupere l'endroit ou la personne voulait aller
    destination_path = stored_location_for(user) || root_path(user)
    # on affiche le message de confirmation et on fait un lien vers la destination
    render :confirmation_sent, locals: { email: , :destination_path }
```
de cette manière tu peux supprimer la methode `connect_france_connect_particulier_redirect`

dans un second temps, tu pourrais faire des helpers pour mutualiser les logiques dans la page pour
```
def sign_only(user)
  sign_out :user if user_sign_in?
  sign_in user
end

def destination_path(user) = stored_location_for(user) || root_path(user)
```

2024-07-23 08:40 UTC, LeSim commented on app/controllers/france_connect/particulier_controller.rb
> +  def set_user_by_confirmation_token
je te propose d'ajouter dans cette methode un check pour s'assurer que `@user` n'est pas nil

```
if @user.nil?
  redirect_to root_path, alert: 'user not found'
```

de cette manière tu peux retirer des `if user.nil?` sur les méthodes qui utilisent `set_user_by_confirmation_token` en before_action

2024-07-23 08:40 UTC, LeSim commented on app/views/france_connect/particulier/confirmation_sent.html.haml
> +  = link_to t('.continue'), france_connect_connect_france_connect_particulier_redirect_path(token: fci.user.confirmation_token), class: 'fr-btn'
est ce qu'il y aurait moyen de renommer cette route `france_connect_connect_france_connect_particulier ...` ?

2024-07-23 14:19 UTC, kara22 commented on app/views/france_connect/particulier/confirmation_sent.html.haml
> +  = link_to t('.continue'), france_connect_connect_france_connect_particulier_redirect_path(token: fci.user.confirmation_token), class: 'fr-btn'
j'ai supprimé la méthode et la route @LeSim

2024-07-24 08:49 UTC, kara22 commented on app/controllers/france_connect/particulier_controller.rb
> +  def connect_france_connect_particulier_redirect
méthode supprimée

2024-07-24 12:50 UTC, LeSim reviewed
toujours pas mais on s'approche

2024-07-24 12:50 UTC, LeSim commented on app/models/france_connect_information.rb
> +      send_custom_confirmation_instructions(user)
je unresolve la conversation car tu as laissé `send_custom_confirmation_instructions`

2024-07-24 13:44 UTC, mfo reviewed
correctif(s)? d'a11y : 
* sujet a11y, un `<fieldset>` doit avoir une `<legend>`, qui n'est pas vide, et un lien doit etre fait entre les deux. donc je te propose deux patch 
  * [0001-a11y-particulier-choose_email-no-empty-legend-ensure.patch](https://github.com/user-attachments/files/16362982/0001-a11y-particulier-choose_email-no-empty-legend-ensure.patch)
  * [0001-a11y-particulier-merge-no-empty-legend-ensure-to-lin.patch](https://github.com/user-attachments/files/16364063/0001-a11y-particulier-merge-no-empty-legend-ensure-to-lin.patch)

2024-07-24 14:18 UTC, mfo commented
amélioration pour la saisie du mail alternatif (on a un 'helper' pour detecter les typos, autant s'en servir ici pour se faciliter la vie au support) : 

[0001-feat-france_connect-choose_email-prevent-bad-email.patch](https://github.com/user-attachments/files/16363455/0001-feat-france_connect-choose_email-prevent-bad-email.patch)

2024-07-24 14:38 UTC, mfo commented
🔴  ETQ usager me connectant avec FC, lorsque je demande a être notifié sur un mail spécifique, si j'utilise un email existant => 500
🟢 ETQ usager me connectant avec FC, lorsque je demande a être notifié sur un mail spécifique, si j'utilise un email existant => je suis encouragé a faire une demande de reset password

<img width="952" alt="Capture d’écran 2024-07-24 à 4 35 37 PM" src="https://github.com/user-attachments/assets/1c532535-3179-4783-ae09-1f9f8db91eec">
[0001-feat-particulier-associate_user-catch-email-already-.patch](https://github.com/user-attachments/files/16363689/0001-feat-particulier-associate_user-catch-email-already-.patch)

2024-07-24 14:52 UTC, mfo commented
J'ai l'impression que l'écran pour choisir son email via une connection FC n'est pas clair :

> <img width="1251" alt="Capture d’écran 2024-07-24 à 4 48 34 PM" src="https://github.com/user-attachments/assets/cd994822-dc0b-4030-8f3a-b25a4db95dbe">

En substance, après une création de compte par email, qui lui est clair :

> <img width="1230" alt="Capture d’écran 2024-07-24 à 4 49 17 PM" src="https://github.com/user-attachments/assets/2179b313-629a-40f3-9b6e-a049bf55fe2b">

@kara22 , moyen que tu clarifies le truc ?

2024-07-24 14:58 UTC, mfo commented
L'écran de demande de confirmation d'email etait un peu brut : 

> <img width="1216" alt="Capture d’écran 2024-07-24 à 4 42 26 PM" src="https://github.com/user-attachments/assets/61b29372-03a7-454c-ac33-8cfd9cd2eac5">

Maintenant il brille 

> <img width="1233" alt="Capture d’écran 2024-07-24 à 4 56 39 PM" src="https://github.com/user-attachments/assets/ed5e7d61-4c0c-44af-920d-608f28f6d20a">

[0001-feat-particulier-confirm_email-nicer.patch](https://github.com/user-attachments/files/16363949/0001-feat-particulier-confirm_email-nicer.patch)

2024-07-24 15:13 UTC, mfo commented
C'est un premier bout de revue fonctionnelle (ac un peu de code ou Sim ne s'etait pas trop exprimé).
Cependant pas facile de relire la ou il y a encore pas mal de suggestion de Sim. 

Je m'arrete la pour le moment. @kara22, souhaites tu merger les patch toi même ou je push ? dis moi ce que tu préfère

2024-07-25 09:19 UTC, kara22 commented on app/controllers/france_connect/particulier_controller.rb
> +  end
ici @user est nil il faut que je le mette dans une variable avec user = fci.user @LeSim

2024-08-08 10:17 UTC, marleneklok commented
Quelques recos ergo/UX (le dernier écran "Confirmez votre adresse / connexion par mail" reste à rediscuter) :
[UX_Connexion avec FranceConnect.pdf](https://github.com/user-attachments/files/16541590/UX_Connexion.avec.FranceConnect.pdf)

2024-08-27 14:50 UTC, tchak commented on app/controllers/france_connect/particulier_controller.rb
> +    if @user.confirmation_sent_at && 2.days.ago < @user.confirmation_sent_at
```suggestion
    if @user.confirmation_sent_at && @user.confirmation_sent_at > 2.days.ago
```

C'est peut-être que moi, mais l'autre forme, je n'arrive pas à passer dans ma tête

2024-08-27 15:02 UTC, tchak commented on app/controllers/france_connect/particulier_controller.rb
> +      flash.alert = I18n.t('france_connect.particulier.flash.merger_token_expired', application_name: Current.application_name)
Par curiosité, pourquoi on change en `I18n.t` ?

2024-08-27 15:03 UTC, tchak commented on app/views/france_connect/particulier/choose_email.html.haml
> +      .fr-fieldset__element.fr-fieldset__element--inline.fr-hidden{ data: { email_france_connect_target: "emailField", controller: 'email-input', email_input_url_value: show_email_suggestions_path }
Je préférerais qu'on utilise `hidden: true, class: 'hidden'` comme on le fait ailleurs dans le code

2024-08-27 15:14 UTC, tchak approved these changes

2024-08-27 15:40 UTC, tchak commented on app/controllers/france_connect/particulier_controller.rb
> +    if @user.confirmation_sent_at && 2.days.ago < @user.confirmation_sent_at
C'est marrant, je viens de remarquer qu'il y a pas mal d'endroits dans le code où c'est fait avec la date en premier. Donc, c'est vraiment moi qui doit avoir un blocage dans la tête. Vous pouvez ignorer.

2024-08-28 08:07 UTC, tchak approved these changes

2024-08-28 08:22 UTC, kara22 commented on app/controllers/france_connect/particulier_controller.rb
> +      flash.alert = I18n.t('france_connect.particulier.flash.merger_token_expired', application_name: Current.application_name)
@tchak parfois une erreur pop sur le linter et indique que la traduction en anglais n'est pas utilisée. Du coup en rajoutant I18n.t cela fixe le problème.

2024-09-05 08:07 UTC, LeSim approved these changes

2024-09-05 08:16 UTC, merged