feat(champs): use new combobox for champs selection multiple
demarches-simplifiees/demarches-simplifiees.fr pull request #10609
Opened 2024-07-15 09:55 UTC by tchak

2024-07-15 14:38 UTC, mfo requested changes
en testant, je me rends compte qu'on ne peut pas supprimer l'unique option d'un choix multiple. pr reproduire : 
1. avoir un choix multiple ac option `[a,b,c...]`
2. choisir une l'option `a`
3. retirer cette l'option `a`
4. recharger la page. l'option `a` est tjr présente

2024-07-15 19:07 UTC, tchak commented
@mfo c'est corrigé

2024-07-16 12:38 UTC, mfo commented on app/javascript/components/ComboBox.tsx
> +          {hiddenInputValues.length == 0 ? (
ok, on avais juste rien a soumettre en l'absence de valeur, ce changement corrige ça

2024-07-16 12:44 UTC, mfo commented on app/javascript/components/react-aria/hooks.ts
>            }
avec les `Combobox/MultiCombobox` qui ont plusieurs `<input type='hidden' />`. on se met a suivre tant la valeur que le nombre d'input par combobox afin de dispatcher l'event

2024-07-16 13:07 UTC, tchak commented on app/javascript/components/ComboBox.tsx
> +          {hiddenInputValues.length == 0 ? (
oui

2024-07-16 13:08 UTC, tchak commented on app/javascript/components/react-aria/hooks.ts
>            }
Je vais ajouter le commentaire. Mais j'ai une idée de comment simplifier (supprimer) ce code. Je ferai une autre PR.

2024-07-16 13:26 UTC, merged