a11y: fix criteria 6.1
demarches-simplifiees/demarches-simplifiees.fr pull request #8146
Opened 2022-11-28 15:00 UTC by colinux

Closes #8050  (page d'accueil + footer)

2022-11-28 21:40 UTC, LeSim approved these changes

2022-11-28 21:40 UTC, LeSim commented on app/helpers/application_helper.rb
> +    "#{APPLICATION_NAME} — #{label}"
question de novice : ca va pas être ennuyeux pour les gens qui utilisent les aria d'avoir à chaque fois l'APPLICATION_NAME avant le label ?

ceux qui n'utilise pas l'aria n'en ont pas besoin

2022-11-29 08:01 UTC, colinux commented on app/helpers/application_helper.rb
> +    "#{APPLICATION_NAME} — #{label}"
Je suis ignorant aussi et ne comprends pas trop l'utilité  de ce préfixe, je vais demander de faire confirmer/valider par @julieSalha

2022-11-29 09:13 UTC, julieSalha commented on app/helpers/application_helper.rb
> +    "#{APPLICATION_NAME} — #{label}"
L'attribut aria-label reprend l'intitulé visible du lien et le précise. Très utile pour les lecteurs d'écran. 
Voici une démo avec Voice Over : 

![IMG_20221129_100516](https://user-images.githubusercontent.com/49035942/204487887-33d1bed5-26ba-44fe-ac04-14030a69024b.jpg)

2022-11-29 09:28 UTC, colinux commented on app/helpers/application_helper.rb
> +    "#{APPLICATION_NAME} — #{label}"
J'ai inversé pour mettre la fonction du lien en premier, et le nom de l'application en suffixe

2022-11-29 10:00 UTC, julieSalha requested changes
- Supprimer l’attribut title lien vers la page d’accueil : Dans le cas d’utilisation d’un attribut aria-label, on évite d’utiliser un attribut title car le premier est mieux pris en compte par les technologies d’assistance. On peut en reparler ensemble...
<img width="1128" alt="Capture d’écran 2022-11-29 à 10 22 55" src="https://user-images.githubusercontent.com/49035942/204497638-ae01b11a-9afb-45c2-a724-a1362c515ad5.png">
(Sur la version française et anglaise)

- Pour l'image-lien beta.gouv.fr placée dans le footer :

1.     Version française : remplacer `title="Le site de beta.gouv.fr — République Française"` par `title="Le site de beta.gouv.fr — Premier Ministre"` (Intitulé du logo placé à gauche)
2. Renseigner l’équivalent pour la version anglaise : 
`title="The Beta.gouv.fr website — First Minister"`

Ou alors remplacer le logo "Premier Ministre" par celui de "République Française".

- Lien "Comment trouver ma démarche ?" : 
Ajouter l'attribut `title="Comment trouver ma démarche ? - Nouvel onglet"` et l'équivalent pour la version anglaise.

2022-11-29 10:57 UTC, julieSalha commented on app/helpers/application_helper.rb
> +    "#{APPLICATION_NAME} — #{label}"
Merci :)

2022-11-29 11:16 UTC, colinux commented
Pour la postérité je l'écris ici : on a finalement suivi la reco du DSFR sur ce lien: pas d'aria-label, mais un seul title plus explicite

2022-11-29 16:09 UTC, julieSalha requested changes
<img width="1121" alt="Capture d’écran 2022-11-29 à 17 03 38" src="https://user-images.githubusercontent.com/49035942/204581039-52ac3548-0000-4edc-a841-424fa7690851.png">

Pour la version française, les corrections ont bien été prises en compte.
Pour le lien "Comment trouver ma démarche ?", remplacer l'attribut `title="Aide pour trouver sa démarche — Nouvel onglet"` par `title="Comment trouver ma démarche ? - Nouvel onglet"`.

Bravo :)

2022-11-30 09:41 UTC, julieSalha approved these changes
Corrections OK. À vérifier en PREPROD. Merci

2022-11-30 09:44 UTC, merged