Adding console output when saving failed
demarches-simplifiees/demarches-simplifiees.fr pull request #8364
Opened 2023-01-04 17:10 UTC by SebastienGt

Ajout de messages d'erreurs dans la console (utile aussi lors des requêtes API) lorsqu'il y a une erreur lors du save pour groupe_instructeur et services.

Et une meilleur pratique avec save! Grâce à cet ajout, les futures erreurs seront détectés plus rapidement. Aujourd'hui elles pourraient se camoufler puisque l'erreur n'est affiché qu'à l'utilisateur sur l'IHM.

2023-01-10 13:41 UTC, LeSim requested changes

2023-01-10 13:41 UTC, LeSim commented on app/controllers/administrateurs/groupe_instructeurs_controller.rb
>      end
bien joué pour le `flash.now`.

Pour le `save!`, je ne comprends pas, dans notre cas :
- si la sauvegarde de ne se fait pas pour une question d'intégrité / validation ,  l'erreur va remonter dans le flash
- si une erreur plus profonde apparaît, genre une perte de connexion db (https://api.rubyonrails.org/classes/ActiveRecord/DatabaseConnectionError.html), l'erreur va être catché plus haut dans la stack et renvoyé à sentry qui est notre outil de monitoring. J'ai l'impression que dans ce code, elle deviendrait invisible

2023-01-10 13:41 UTC, LeSim commented on app/controllers/administrateurs/groupe_instructeurs_controller.rb
> +        flash.now[:alert] = @groupe_instructeur.errors.full_messages
mm remarque, bien joué pour le now, pour le reste, je suis septique.

2023-01-12 15:44 UTC, SebastienGt commented on app/controllers/administrateurs/groupe_instructeurs_controller.rb
>      end
Bonjour,

Merci, pour le retour. Le reste était utile seulement dans notre cas (instance MinArm)
J'ai modifié la MR pour qu'il y'ait que les flashs.now.

2023-01-13 11:12 UTC, tchak commented on app/controllers/administrateurs/groupe_instructeurs_controller.rb
> +        flash.now[:notice] = "le groupe « #{@groupe_instructeur.label} » a été supprimé#{routing_notice}."
ici on fait un redirection donc pas besoin de `now`

2023-01-18 08:51 UTC, tchak approved these changes

2023-01-18 09:13 UTC, tchak approved these changes

2023-01-18 09:13 UTC, merged