Us/poc multiple - suivre les dossiers
demarches-simplifiees/demarches-simplifiees.fr pull request #8379
Opened 2023-01-06 09:44 UTC by lisa-durand

Mise en place de l'action multiple "accepter"
Voir https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/8076

<img width="1193" alt="Capture d’écran 2023-01-06 à 10 42 28" src="https://user-images.githubusercontent.com/6756627/210974686-d20f0de9-2ec9-46a5-ac1f-7634a0663b46.png">

2023-01-06 09:46 UTC, lisa-durand commented on app/models/batch_operation.rb
> +      query.without_followers
pas sur de la pertinence / de l’intérêt de ce scope.

2023-01-06 10:22 UTC, mfo requested changes

2023-01-06 10:22 UTC, mfo commented on app/models/batch_operation.rb
> +      query.without_followers
```suggestion
      query.without_followers.en_cours
```
cf: https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/3dbfd81d95f9ed6758b41309c71b0d64783caffb/app/models/dossier.rb#L410

2023-01-09 10:56 UTC, mfo approved these changes

2023-01-09 10:58 UTC, merged