a11y : add scrolling functionnality for description procedure
demarches-simplifiees/demarches-simplifiees.fr pull request #8629
Opened 2023-02-14 12:11 UTC by julieSalha

[Script compatible avec les technologies d'assistance (Critère 7.1) - Création dossier (Identité)#8118](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/8118)

2023-02-14 13:00 UTC, mfo commented
en gros on rend le truc façon accordéon scrollable ? j'ai une curiosité, en dehors du standard, pas moyen d'en faire qqch de juste ni scrollable, ni expandable ? en gros, j'ai l'impression que les scroll 'in page', c'est nul. devrions nous mettre @Olivier-Marcellin dans la boucle ?

2023-02-14 13:03 UTC, krichtof commented on config/locales/en.yml
> -      label_modal: "Burger menu"
J'ai peut⁻etre mal regardé mais j'ai l'impression que la clé label_modal est présente uniquement en français, et manquante maintenant en anglais ?

2023-02-14 13:39 UTC, julieSalha commented on config/locales/en.yml
> -      label_modal: "Burger menu"
La clé label_modal pour le burger menu est inutile, je l'ai supprimé sur un ancien ticket.

2023-02-15 08:30 UTC, colinux commented
@mfo on en avait justement déjà parlé avec Olivier, et là c'était le moins mauvais compromis qu'on a trouvé a11y/mobile/UX pour les longues descriptions. Cette page est provisoire car la nouvelle page d'accueil de démarche ne contiendra plus de description complète sous cette forme (sauf pour les anciennes démarches), et il n'y aura donc plus ce besoin.

2023-02-15 08:34 UTC, colinux requested changes
petit fix de traduction

2023-02-15 08:34 UTC, colinux commented on config/locales/fr.yml
> +          description: Description de la procédure
```suggestion
          description: Description de la démarche
```

2023-02-15 10:34 UTC, julieSalha reviewed
Ok pour la traduction

2023-02-15 11:19 UTC, colinux approved these changes

2023-02-16 10:52 UTC, merged