[WIP] Instructeur: flag dossier as resolvable
demarches-simplifiees/demarches-simplifiees.fr pull request #8714
Opened 2023-02-28 18:18 UTC by colinux

2023-04-13 07:49 UTC, mfo commented on app/components/dossiers/message_component/message_component.html.haml
> +        = t('.flagged_pending_corrections')
idéalement aligner les wordings entre le label a coté du titre du dossier, le label dans le tableau et le label dans la messagerie

2023-04-13 07:51 UTC, colinux commented on app/views/instructeurs/dossiers/_instruction_button.html.haml
> +      = dossier.en_instruction? ? "Instruire le dossier" : "Demander une modification"
wording correction

2023-04-13 08:14 UTC, colinux commented on db/migrate/20230228134859_create_dossier_corrections.rb
> +      t.datetime :resolved_at, precision: 6
rajouter index sur resolved_at

2023-04-13 08:23 UTC, colinux commented on app/views/instructeurs/dossiers/_instruction_button.html.haml
> +      = dossier.en_instruction? ? "Instruire le dossier" : "Demander une modification"
+ role region avec même condition

2023-04-13 08:41 UTC, mfo commented on config/locales/views/dossier_mailer/notify_pending_corrections/en.yml
> +        In order to continue its instruction, <strong>an instructor asks you to edit information</strong> to your file no. %{dossier_id} of the « %{libelle_demarche} » procedure.
```suggestion
        In order to continue its instruction, <strong>an instructor requested you to edit information</strong> to your file no. %{dossier_id} of the « %{libelle_demarche} » procedure.
```

2023-04-13 08:48 UTC, mfo commented on spec/services/dossier_projection_service_spec.rb
> +      context 'for dossier reolutions table' do
```suggestion
      context 'for dossier resolutions table' do
```

2023-04-18 13:59 UTC, colinux commented on spec/components/instructeurs/instruction_menu_component_spec.rb
adaptation des specs du partial avant refacto en component

2023-04-19 11:38 UTC, mfo commented on app/components/instructeurs/en_construction_menu_component/en_construction_menu_component.en.yml
> +  revert_en_construction: Revert en construction
```suggestion
  revert_en_construction: Revert to in progress
```

2023-04-19 11:45 UTC, mfo commented on app/views/instructeurs/procedures/show.html.haml
> +                    = link_to_if(p.hidden_by_administration_at.blank?, safe_join(status), path, class: class_names("cell-link": true, "fr-py-0": status.many?))
je connassais pas c'est top ! ❤️

2023-04-19 11:48 UTC, mfo requested changes
juste une typo dans les trads. sinon canon le refacto

2023-05-24 16:56 UTC, colinux commented on config/locales/fr.yml
> -        configure_api_particulier_token: "Configurer le jeton API particulier"
clés en doublon, cf ligne 802

2023-05-31 15:56 UTC, mfo approved these changes

2023-06-05 08:15 UTC, merged

2023-06-08 09:06 UTC, Olivier-Marcellin commented
Je compile ici l'ensemble de mes remarques et captures écrans à partir des maquettes sur Figma sur la conception en cours sur le SVA côté admin :

Page Les démarches à suivre onglet suivi :
- ajout d'un badge “Attente SVA” dans la colonne statut et icône time
- ajout d'une colonne “Décision SVA” à la suite

- icône timer dans le badge décision SVA
- badge de couleur jaune pour le badge en instruction, rose en construction, vert accepté avec icône success (reste le bleu pour les formulaires en brouillon côté usager)
- simplification de la colonne “Actions de suivi” via des icônes seules en guise de bouton

wording pour les badges de la colonne décision SVA :
- badge “J+6 après correction“
- badge J+1
- badge J+2
- badge J+55 (également en rouge pour n'avoir que deux niveaux = ce qui doit être modifié/autre cas)
- Déposé avant SVA (ok en gris)

Page de contenu de dossier onglet demande :

- wordings du menu déroulant réajustés
- CTA “Valider la demande de correction”

<img width="1057" alt="Capture d’écran 2023-06-08 à 11 01 27" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/e636d818-92b7-47ce-a462-4115cd64209d">
<img width="1062" alt="Capture d’écran 2023-06-08 à 11 05 07" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/9e8825d9-61ec-471b-9672-a8a06e680fd4">

Voir les maquettes https://www.figma.com/file/NXt3KjxXdQCbNGh3mru7SY/Dossiers-en-SVA%2FSVR?type=design&node-id=1%3A2&t=FXIOXY4NLerNtc9q-1

2023-06-08 09:11 UTC, Olivier-Marcellin commented
La suite de mes remarques côté usagers :

Tableau de bord :

- message composant dsfr Alerte dans la card
- case à cocher “Remonter les dossiers à corriger” ou autre proposition (règle d'affichage = par défaut les dossiers à corriger sont en haut de la pile)
- indication de la date limite de corrections dans le message d'alerte (la date limite en dehors par exemple dans un badge pourrait être plus confusant)
<img width="608" alt="Capture d’écran 2023-06-08 à 11 07 48" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/888adc84-fcd8-41a2-91ce-1001a1663226">

2023-06-08 09:15 UTC, Olivier-Marcellin commented
Autre remarques toujours côté usagers dans le formulaire :

- plutôt que un badge un message d'alerte et une ancre qui renvoie vers la messagerie
- case à cocher “je certifie avoir effectué toutes les corrections…” à la fin du formulaire
<img width="476" alt="Capture d’écran 2023-06-08 à 11 12 20" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/f3c8cbf8-2fd3-440b-afee-7bed4a37d059">
<img width="536" alt="Capture d’écran 2023-06-08 à 11 13 17" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/ba8280d2-a5d6-4033-8c22-31c3590d80de">

- CTA “Déposer le dossier” (pas nécessaire d'avoir un wording spécifique car l'usager doit redéposer le dossier dans tous les cas
<img width="498" alt="Capture d’écran 2023-06-08 à 11 13 32" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/c8b55ab6-5cd9-450e-80b9-a2f81f616786">

PS dans les maquettes le formulaire est à étapes et il comporte une page récapitulative (c'est une proposition d'amélioration qui viendrait plus tard)

2023-06-08 17:05 UTC, Olivier-Marcellin commented
autre retour aujourd'hui avec une proposition de réajustement des colonnes du tableau côté admin : compiler les actions de suivi dans un menu positionné au dessus (ce qui nécessite cependant pour l'instructeur de sélectionner une ligne de dossier) mais qui permettrait de gagner de la place dans le tableau et d'avoir des intitulés lisibles et de rassembler d'autres actions disséminés dans la page.
<img width="762" alt="Capture d’écran 2023-06-08 à 19 01 12" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/101646817/7d6e4526-7722-4758-b6df-be455554f91a">