[instructeurs] Je peux poser une question dans une demande d'avis
demarches-simplifiees/demarches-simplifiees.fr pull request #8743
Opened 2023-03-06 10:08 UTC by lisa-durand

#8512

2023-03-13 09:13 UTC, colinux requested changes
Quelques petits ajustements techniques, mais sinon ça me paraît bien. 
On peut aussi préciser dans le form instructeur qu'il s'agit d'une question optionnelle, dont l'expert répondra par oui ou non (afin d'orienter la question).

2023-03-13 09:13 UTC, colinux commented on app/controllers/concerns/create_avis_concern.rb
> +      return Avis.new(create_avis_params)
Il y a moyen d'utiliser le système de génération de message automatique de Rails plutôt que créer nos propres textes : 

```ruby
if create_avis_params[:emails].empty?
  avis = Avis.new(create_avis_params)
  errors = avis.errors
  errors.add(:emails, :blank)

  flash.alert = errors.full_message(:emails, errors[:emails].first)

  return avis
```

Ce serait encore plus simple si on avait un validateur de presence dans le modèle sur le champ `email`, mais c'est peut-être pas anodin qu'il n'y soit pas, d'autant que pour le formulaire c'est un champ emails au pluriel

2023-03-14 10:27 UTC, lisa-durand commented on app/views/experts/avis/instruction.html.haml
> +    = render partial: 'experts/avis/shared/list', locals: { avis: @dossier.avis_for_expert(current_expert), avis_seen_at: nil }
en effet - c'etait pas hyper clair cette partie car j'ai l'impression qu'il y avait : 
- des fichiers en trop (que j'ai supprimé)
- des fichiers dupliqués (à qq éléments près)
Du coup, j'ai essayé de pas tout casser dans cette 1ere PR et ça m'a paru plus simple de juste harmoniser les chemins entre experts et instructeurs. 
J'aimerais par la suite dans une 2e PR, toucher à l'interface, scinder les vues et la en profiter pour toucher un peu plus à "l'architecture" et à mon avis fusionner ces fichiers "shared" qui sont sensiblement les mm - mis à part les actions spécifiques aux instructeurs.

2023-03-14 14:12 UTC, colinux commented on app/views/experts/avis/instruction.html.haml
> +    = render partial: 'experts/avis/shared/list', locals: { avis: @dossier.avis_for_expert(current_expert), avis_seen_at: nil }
OK, comme tu veux :) Là je parlais même pas de réutilisation ou non, mais simplement du fait qu'actuellement les partials ne sont pas partagés, donc ils pourraient être hors de shared. Mais OK si t'envisages une refonte plus tard c'st top top top !

2023-03-14 16:17 UTC, colinux approved these changes
J'y pense, il manque l'intégration dans le PDF.  (vers la ligne 200 de app/views/dossiers/show.pdf.prawn)
(les avis n'y sont visibles que pour les instructeurs)

Sinon ça m'a l'air tout bon, bravo!

2023-03-14 16:17 UTC, colinux commented on config/locales/models/avis/fr.yml
> +      question_label_hint: (champ optionnel) l'expert pourra répondre par oui/non
micro détail: Olivier veut pousser partout le terme "(facultatif)" et le mettre en fin du label ou hint pour harmoniser toutes les interfaces.

2023-03-14 16:17 UTC, colinux requested changes
(je remets en request changes, je m'étais trompé de bouton)

2023-03-16 10:10 UTC, lisa-durand commented
@colinux Merci pour les retours et bien vu pour le PDF - je l'avais pas du tout en tête.
Le rendu est pas dingue mais je me dis que ça fait le job. J'ai hésité à ajouter la question mais j'ai peur que ce soit trop redondant et elle ne l'était pas avant. Donc je me dis qu'avec le texte de réponse ça peut déjà donner du contexte. Je ne sais pas ce que tu en penses ?
<img width="411" alt="Capture d’écran 2023-03-16 à 11 04 54" src="https://user-images.githubusercontent.com/6756627/225584513-ace3cc28-5060-45c5-a139-86275e537565.png">

2023-03-17 12:02 UTC, colinux approved these changes

2023-03-17 15:19 UTC, merged