refactor(commune): chose commune by postal code
demarches-simplifiees/demarches-simplifiees.fr pull request #8783
Opened 2023-03-20 18:56 UTC by tchak

<img width="416" alt="CleanShot 2023-03-20 at 19 54 08@2x" src="https://user-images.githubusercontent.com/12428/226438649-05de215c-e309-495d-a38a-4d493f33947b.png">

<img width="431" alt="CleanShot 2023-03-20 at 19 55 01@2x" src="https://user-images.githubusercontent.com/12428/226438814-3325e669-1761-44d3-9c36-25b13a620341.png">

<img width="591" alt="CleanShot 2023-03-20 at 19 53 36@2x" src="https://user-images.githubusercontent.com/12428/226438549-2f721ffa-1482-4b68-a78e-f22ee94b436b.png">

<img width="762" alt="CleanShot 2023-03-20 at 19 55 34@2x" src="https://user-images.githubusercontent.com/12428/226438924-e2241095-70fe-4387-b2ea-49ef1e73c6f5.png">

<img width="476" alt="CleanShot 2023-03-20 at 19 54 39@2x" src="https://user-images.githubusercontent.com/12428/226438735-657c7623-227a-498d-8e46-faac02fde9da.png">

2023-03-20 20:19 UTC, LeSim commented
Supa nice ! Je suis curieux, t'as piqué l'implem de qq  ? (hormis de nous pour les choix multiples ?)

2023-03-21 08:09 UTC, LeSim commented
Je me demande s'il ne faudrait pas une phrase type `Veuillez précisez` entre le code postal et choix multiple. un avis @Olivier-Marcellin ?

2023-03-21 08:27 UTC, LeSim reviewed
Est ce que tu pourrais couper en plusieurs commits stp. au moins sur la partie changement de model puis shootage de react.

2023-03-21 08:27 UTC, LeSim commented on app/models/champs/commune_champ.rb
> +  def code_postal_with_fallback
J'ai l'impression que le code_postal_with_fallback est une string particulière renvoyée par l'api géo. Est ce que tu pourrais mettre un exemple en commentaire ?

2023-03-21 08:54 UTC, tchak commented on app/models/champs/commune_champ.rb
> +  def code_postal_with_fallback
C'est surtout un hack le temps de migrer les data. Mais oui je vais ajouter des commentaires.

2023-03-21 16:59 UTC, colinux commented
Top. Perso je suis fan de ce workflow, plusieurs sites l'utilisent (les impots entre autres,) et je le trouve toujours simple. Dans les rares cas où je dois saisir une commune qui n'est pas la mienne, c'est trivial de chercher le code postal ailleurs.

Le pb de rechercher avec le nom c'est qu'il ya de beaucoup de communes homonymes, et c'est le CP qui discrimine de toute façon (et l'usager doit être vigilant à valider le bon). Sans parler de tous les "saint quelque chose" où l'utilisateur doit taper pas mal de lettres avant d'avoir des choix pertinents.

2023-03-22 09:42 UTC, tchak commented on app/models/champs/commune_champ.rb
> +  def code_postal_with_fallback
j'ai mis un commentaire

2023-03-27 08:11 UTC, colinux requested changes

2023-03-27 08:11 UTC, colinux commented on app/components/editable_champ/communes_component/communes_component.html.haml
> +%label.notice{ for: code_postal_input_id } Code postal de la commune
Un peu d'i18n ? ;) (+ 5 lignes plus bas)

2023-03-29 07:04 UTC, colinux approved these changes
Dernier petit oubli de trad (cf suggestion), et c'est bon pour moi

2023-03-29 07:04 UTC, colinux commented on app/components/editable_champ/communes_component/communes_component.en.yml
> +  postal_code: Code postal de la commune
```suggestion
  postal_code: Postal code of the municipality
```

2023-03-29 13:58 UTC, merged

2023-03-30 16:08 UTC, Olivier-Marcellin commented
hello, je reprends le fil de votre ticket avec les remarques suivantes :
y a un problème de méthode avec une conception faite sans échanger ensemble au préalable (ça pose une difficulté de venir après de mon côté plutôt que au début)

on a un label Commune :
mais on demande à l'utilisateur de saisir un code postal
peut-on saisir une commune ?
si oui le label devrait être : “Code postal, ville ou commune” et si non : “Code postal”

dans le cas contraire, je ne comprends pas pourquoi on demande à l'usager de saisir un code postal pour une commune

ensuite, je me demande comment l'usager fait s'il vit à l'étranger ? par exemple avec cette adresse : 
64 Fifth Avenue
New York NY 10010
USA

enfin, quelle suite dans le cas d'une erreur 'aucune commune trouvée pour le code 7577' dans mon exemple (peut être un peu tordu 10010 correspond en France à Troyes et à l'étranger NY

2023-03-31 09:09 UTC, tchak commented
> y a un problème de méthode avec une conception faite sans échanger ensemble au préalable

Pour moi, ce n'est pas de la conception, mais de la correction de bug. Le champ dans l'état nous pose beaucoup de problèmes et ce changement est surtout un pansement. Nous allons continuer à itérer sur ce que nous voulons éventuellement, mais les champs autocomplete seront compliqués à court terme. Nous avons deux options : attendre que DSFR le fasse et espérer que ce qu'ils feront satisfasse notre usage, ou investir nous-mêmes pour implémenter un autocomplete qui réponde à nos besoins. Les deux prendront du temps. En attendant, nous sommes obligés de faire des compromis pour avoir quelque chose d'utilisable et qui ne nous bloque pas sur le plan téchnique.

Le libellé "Commune" est un (mauvais) exemple. C'est le titre rédigé par l'administrateur. Souvent, il sera plutôt "Commune de rattachement du centre de traitement" ou "Quelle est la commune concernée par le projet ?". Le libellé rédigé par l'administrateur est lié au select de la commune et pas au champ du code postal qui a son propre libellé ("Code postal de la commune") non modifiable par l'administrateur, comme nous le faisons pour les autres descriptions du format.

> comment l'usager fait s'il vit à l'étranger

Les communes étrangères ne sont pas gérées par ce champ. C'est déjà le cas actuellement. Introduire de la gestion de communes étrangères serait compliqué et surtout produirait des valeurs non vérifiées pour les administrateurs dans des formulaires qui n'en ont pas besoin. Et avoir ça en option me semble redondant avec le conditionnel. Mais nous pouvons en parler lorsque nous travaillerons sur l'adresse internationale.

Je comprends la frustration. Je ne veux vraiment pas que ça soit vu comme du "design sauvage", mais plutôt une tentative de combler un problème en attendant une meilleure solution. Je propose plusieurs actions :
- faire un point pour voir si nous pouvons améliorer la version sans autocomplete (améliorer les libellés et les messages d'erreurs)
- faire un point pour décider de comment progresser pour avoir un composant autocomplete qui nous satisfasse sur le plan technique, de l'accessibilité et de l'UX
- le jour où nous aurons ce composant, je suis prêt à aller réimplémenter tous les champs que tu veux en l'utilisant :)

2023-03-31 16:15 UTC, Olivier-Marcellin commented
hello Paul, merci pour ton bon retour et pour nos échanges, voici en retour mes préconisations pour le wording :
- Libellé du champ : Commune (pré-rempli mais customisable)
- Description du champ : Renseignez le code postal de la ville puis sélectionnez la commune dans la liste (non customisable)
- Message d'erreur sur le champ saisie du code postal : Le code postal n’est pas valide. Vérifier le code postal
- Message d'erreur sur le sélect commune : à priori impossible puisque le code postal est forcément en lien avec une commune, mais si tel était le cas on pourrait avoir : Aucun résultat. Vérifier le code postal

En m'inspirant de ton design, voici une maquette :
<img width="372" alt="Capture d’écran 2023-03-31 à 18 13 49" src="https://user-images.githubusercontent.com/101646817/229174322-623819e9-d141-4b87-8eb6-b31c005a0465.png">