a11y - 8589 accessibility statement (static page)
demarches-simplifiees/demarches-simplifiees.fr pull request #8800
Opened 2023-03-22 16:11 UTC by julieSalha

[Pages Déclaration d’accessibilité et Mentions légales (hors Gitbook)#8589](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/8589)

2023-03-23 08:53 UTC, colinux approved these changes
Globalement ça me va, je te fais 100% confiance sur le contenu, et quelques petites questions / remarques mineures pour l'html :)  Et bravo pour tout ce contenu !

Sinon tu as bien dû t'embêter avec toutes les traductions et la gestion des clés. J'aurais du y penser avant pour t'en parler quand tu as fait les mentions légales mais il y a une autre moyen bien plus adapté aux pages statiques : plutôt qu'avoir un seul fichier qui importe clé par clé les traductions et qui rend l'intégration et maintenance très lourde et propice aux erreurs, techniquement ça aurait pu se faire avec une vue par langue, (le nom du fichier de la vue intègre la locale), et on écrit dans chaque fichier directement le texte dans la bonne langue. 

Par exemple: 

```erb
# fichier accessibility_statement.fr.html.haml (note qu'on a "fr" dans le nom)
%h1 Déclaration d'accessibilité
...
```

```erb
# fichier  accessibility_statement.en.html.haml
%h1 Accessibility statement
...
```

Ainsi pas besoin de `t("..")` et de clés dans les fichiers de locale, car Rails automatiquement renvoie la bonne vue en fonction de la locale. Ça permet aussi d'avoir potentiellement un contenu plus spécifiquement adapté langue par langue (que ce soit des paragraphes différents, des liens différents etc…)


Je dis pas qu'il faut faire ces changements maintenant que tu as fait tout ce travail (sauf si vraiment tu te sens motivée!) mais ça pourrait servir plus tard pour d'autres pages.

2023-03-23 08:53 UTC, colinux commented on app/controllers/accessibility_statement_controller.rb
> +end
fichier inutile ;)

2023-03-23 08:53 UTC, colinux commented on app/views/static_pages/accessibility_statement.html.haml
> +    .accessibility-block
que fait cette classe, utilisée à plusieurs endroits ? Si c'est juste pour encapsuler dans un div, sans css, on peut se contenter d'un `%div`
Même remarque plus hbas pour `.no-accessible` et `.technos-list`

2023-03-23 08:53 UTC, colinux commented on app/views/static_pages/accessibility_statement.html.haml
> +  .fr-container
tu verras pour les mentions légales, j'ai fait une petite modif pour utiliser le système de grille et colonnes pour améliorer la responsivité. C'est peut-être moins nécessaire ici car on exploite plus la largeur de l'écran, par rapport à l'autre page

2023-03-23 09:40 UTC, colinux requested changes
Bon en fait en regardant de près le contenu cette fois, je me rends compte qu'il y a des trucs à changer avec les liens. J'ai essayé de lister tout ce que j'ai vu , en gros il y a 3 catégories de problèmes : 

- pas de chemin absolu tant qu'on reste sur www.demarches-simplifiees.fr => mais les path rails à la place
- pour certaines pages, les urls sont personnalisables par les instances, donc on doit les utiliser plutôt que mettre "en dur" les chemins
- des liens ne sont pas possibles car accessibles uniquement une fois connecté, et/ou rattaché à ton compte/ton dossier.

Dispo si t'as besoin d'assistance dans tout ça

2023-03-23 09:40 UTC, colinux commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_five.label"), t("views.accessibility_statement.preparation.page_five.url")
```suggestion
          = link_to t("views.accessibility_statement.preparation.page_five.label"), new_user_session_path
```

2023-03-23 09:40 UTC, colinux commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/contact"
```suggestion
```

2023-03-23 09:40 UTC, colinux commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/"
```suggestion
```

Pas d'url absolue quand c'est directement chez nous, que ce soit pour les instances ou même pour le dev.

Tant que c'est sur le même domaine, il vaut mieux que la vue utilise les chemins générés par rails, plutôt que passer par la traduction, par exemple `root_path` pour la page d'accueil, `contact_path` . On a aussi d'autres pages dont les urls sont personnalisables lorsqu'elles sont externalisées par les autres instances DS. (cf commentaire plus bas)

2023-03-23 09:40 UTC, colinux commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/declaration-accessibilite"
```suggestion
```

2023-03-23 09:40 UTC, colinux commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/users/sign_in "
```suggestion
```

2023-03-23 09:40 UTC, colinux commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/dossiers"
```suggestion
```

2023-03-23 09:40 UTC, colinux commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/dossiers/10659723/messagerie"
On ne peut pas intégrer toutes ces pages qui se rapportent à un dossier : elles sont spécifiques à ton compte (et à ton n° dossier), et provoqueront une erreur pour tout le monde. Ces pages ne sont pas accessibles autrement qu'après avoir commencé un dossier pour une démarche donnée.

2023-03-23 09:40 UTC, colinux commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_six.label"), t("views.accessibility_statement.preparation.page_six.url")
```suggestion
          = link_to t("views.accessibility_statement.preparation.page_six.label"), dossiers_path
```
mais cette page provoquera une erreur lorsqu'on n'est pas connecté, donc je crois pas qu'il faille faire de liens

2023-03-23 09:40 UTC, colinux commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_ten.label"), t("views.accessibility_statement.preparation.page_ten.url"), title: t("views.accessibility_statement.preparation.pag
Les instances n'ont pas cette doc mais une autre qui leur est propre, avec leur propre contenu et urls. Pour le moment je ne sais pas comment on doit gérer ça. J'ai pas de solution simple pour le moment

2023-03-23 09:40 UTC, colinux commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_twelve.label"), t("views.accessibility_statement.preparation.page_twelve.url")
Cf remarques dans les traductions: on ne peut pas lister de pages spécifiques à un compte

2023-03-23 09:40 UTC, colinux commented on config/locales/fr.yml
> +          url: "https://github.com/betagouv/demarches-simplifiees.fr/issues?q=accessibilit%C3%A9+"
```suggestion
          url: "https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues?q=accessibilit%C3%A9+"
```

2023-03-23 14:11 UTC, julieSalha commented on app/views/static_pages/accessibility_statement.html.haml
> +          = mail_to "contact@demarches-simplifiées.fr"
Pris en compte :)

2023-03-23 14:14 UTC, julieSalha commented on app/views/static_pages/accessibility_statement.html.haml
> +          = phone_to "0171210170", "+33 (0) 1 71 21 01 70"
Pris en compte :)

2023-03-23 14:22 UTC, julieSalha commented on config/locales/fr.yml
> +      line_two: "Cette déclaration d’accessibilité s’applique à Démarches simplifiées (demarches-simplifiees.fr)."
J'ai supprimé l'URL :)

2023-03-23 15:17 UTC, julieSalha commented on config/locales/links.en.yml
> +        url: "https://www.demarches-simplifiees.fr/declaration-accessibilite"
ok

2023-03-23 15:18 UTC, julieSalha commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_three.label"), t("views.accessibility_statement.preparation.page_three.url")
ok.

2023-03-23 15:21 UTC, julieSalha commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_five.label"), t("views.accessibility_statement.preparation.page_five.url")
pris en compte :)

2023-03-23 15:22 UTC, julieSalha commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/"
pris en compte :)

2023-03-23 15:22 UTC, julieSalha commented on config/locales/fr.yml
> +          url: "https://www.demarches-simplifiees.fr/users/sign_in "
ok

2023-03-23 15:32 UTC, julieSalha commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_six.label"), t("views.accessibility_statement.preparation.page_six.url")
Lien supprimé :)

2023-03-23 15:38 UTC, julieSalha commented on app/views/static_pages/accessibility_statement.html.haml
> +          = link_to t("views.accessibility_statement.preparation.page_ten.label"), t("views.accessibility_statement.preparation.page_ten.url"), title: t("views.accessibility_statement.preparation.pag
J'ai supprimé les liens dans un premier temps...

2023-03-27 10:27 UTC, colinux approved these changes

2023-03-27 11:36 UTC, merged