correctif(expert/avis#index): ETQ expert, je veux retrouver mes avis donnés sur des dossiers traités
demarches-simplifiees/demarches-simplifiees.fr pull request #9054
Opened 2023-05-16 12:43 UTC by mfo

see: https://secure.helpscout.net/conversation/2242876650/2029514?folderId=1653799

2023-05-16 16:25 UTC, lisa-durand commented on app/controllers/experts/avis_controller.rb
> -      avis = current_expert.avis.not_revoked.not_termine.includes(dossier: [groupe_instructeur: :procedure]).not_hidden_by_administration
Bien vu ! 
Par contre ça crée un autre bug 😅 Car on ne scinde pas les avis "donnés" et "à donner".
On veut afficher les "donnés" mais pas les "à donner" si les dossiers sont "terminés"

**Illustration du bug :** 
Dans l'index on nous dit 1 avis à donner et lorsqu'on clique on arrive sur 0 avis à donner
<img width="819" alt="Capture d’écran 2023-05-16 à 18 19 20" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/86bae334-c774-491c-bdfc-b288800bf7dc">

<img width="776" alt="Capture d’écran 2023-05-16 à 18 19 27" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/895ece3c-e56e-4bba-b43c-651163083c79">

2023-05-16 16:27 UTC, lisa-durand requested changes
je t'ai fait un commentaire direct sur la ligne correspondante

2023-05-20 06:30 UTC, mfo commented on app/controllers/experts/avis_controller.rb
> -      avis = current_expert.avis.not_revoked.not_termine.includes(dossier: [groupe_instructeur: :procedure]).not_hidden_by_administration
c'est clair merci @lisa-durand  ! je vais me debrouiller pr mieux gérer ce compteur.

2023-05-22 08:51 UTC, mfo commented on app/controllers/experts/avis_controller.rb
> -      avis = current_expert.avis.not_revoked.not_termine.includes(dossier: [groupe_instructeur: :procedure]).not_hidden_by_administration
le bug : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9054/commits/00841070f44e3118b217f75e20e14f4885021471 
le correctif : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9054/commits/09d895eb99f3948fb9c353524d6216d07b81a33d

bon pour toi @lisa-durand ?

2023-05-22 09:20 UTC, lisa-durand commented on app/views/experts/avis/index.html.haml
> +              %li.avis-a-donne
il y a une erreur sur le nom de la classe j'ai l'impression

2023-05-22 09:25 UTC, lisa-durand approved these changes
Je t'ai fait un petit commentaire sur un nom de classe mais sinon ça m'a l'air top !

2023-05-23 09:07 UTC, merged