[Export] Créer une page d'export et sortir les liens des dropdowns
demarches-simplifiees/demarches-simplifiees.fr pull request #9473
Opened 2023-09-11 14:45 UTC by lisa-durand

closes #9368 

<img width="1267" alt="Capture d’écran 2023-09-18 à 17 10 31" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/b9e1b0cf-ac8f-4b00-abf6-2ba5b74b8d0e">

![Capture d’écran 2023-09-21 à 14 30 20](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/150279/a3bf272f-ca59-45e1-a412-579006f91fd9)

Reste à faire

- [x] Système de "notification" : 
    - [x] Basique dans cette PR quand un export est terminé (pastille sur le lien "voir les exports" quand un nouvel export n'a pas encore été vu). On se sert (provisoirement ?) d'un cookie à durée de vie courte (3j, à peine > à la rétention des exports)
    -  [ ] Avancé éventuellement plus tard : une vraie "alerte", limitée aux exports demandés par l'instructeur connecté (on ne notifie pas d'exports générés par d'autres instructeurs du même groupe). Peut-être aussi: enregistrer le statut téléchargé ou non pour conditionner l'affichage, ce qui pourrait supprimer le besoin du cookie. Dans une autre PR.
- [x] Clarifier l'UX de la nouvelle page exports
- [x] Mettre à jour les messages Flash alert avec le lien vers la page export
- [x] Verifier si le turbo-poll fonctionne
- [x] Tests de cette page exports
- [ ] Ajouter en bas quelques infos pratiques et astuces en cas d'erreur, warning macros, lien vers la doc etc… (cf point tech 20/09). Une autre PR ?

2023-09-21 08:20 UTC, mfo commented on app/controllers/instructeurs/procedures_controller.rb
> +      scope = scope.where(updated_at: last_seen_at...) if last_seen_at
je connaissais pas cette synthax de `date...` pour créer un range. Super esthétique !

2023-09-21 08:30 UTC, mfo commented on app/models/export.rb
>      if export.available? && export.old? && force
```suggestion
    if export.available? && export.old? || force
```

pas de votre faute, mais en testant, je me rends compte qu'on peut uniquement forcer la re-génération d'un export si celui ci `export.available? && export.old? && force` (cas du bouton regenerer l'export qui est un refresh dans l'ui), ne souhaiterions nous pas permettre de re-generer un export qui fait que planter ?

2023-09-21 08:39 UTC, mfo commented on app/components/dossiers/export_link_component/export_link_component.html.haml
> +        - if export.old? || export.failed?
ça va de pair avec mon autre commenaitre : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9473/files#r1332682463

2023-09-21 08:49 UTC, mfo requested changes
déjà bravo car l'ui/l'ux me semble canon 😍 

Aussi, en sorti d'UI/UX canon, c'est vraiment top cette page qui liste TOUS les exports car ça evite la gymnastique/compléxité bizarre du `find_for_groupe_instructeurs` et ce qui découlait derrière avec les boutons etc... 👏 

Je pense qu'il y a : 
* ce petit point de secu (transmis en patch par mattermost pour pas polluer votre taff) 
* le fait de pouvoir regenerer un export quand il est fail (deux commentaires la dessus).
* aussi quand je demande la création d'un export, deux exports s'affichent dans mon UI
* a clarifier la difference entre le bouton pour télécharger tous les dossiers (incluant ceux archivés, donc bouton en haut de page) et le bouton pour télécharger tous les dossiers de l'onglet au total (qui n'inclut pas les dossiers archivés)

2023-09-21 09:55 UTC, LeSim commented
C'est magnifique !
un ptit point de compréhension :

"Export .ods d'e 5 dossiers au total" , je ne comprends pas si c'est un export de tous les dossiers au total, si c'est 5 dossiers parmi d'autre. 

et du coup, moi qui suis un instructeur qui veut tous les dossiers, je ne sais pas si je peux réutiliser ce lien ou si je dois faire un nouvel export.

2023-09-21 12:01 UTC, colinux commented on app/controllers/instructeurs/procedures_controller.rb
> +      scope = scope.where(updated_at: last_seen_at...) if last_seen_at
oui, j'adore et en plus c'est de l'optimisation active record (évite de parser un string avec la colonne et l'opérateur >=…)
`date...` c'est un range exclusif, donc >
`date..` c'est un range inclusif, donc >=

2023-09-21 13:25 UTC, colinux commented on app/models/export.rb
>      if export.available? && export.old? && force
En creusant ce sujet et les raisons qui font qu'on peut redemander un export, je m'aperçois que le "problème" est plus profond : 

- le fait de détruire l'export précédent le fait disparaître de la liste des exports ; ça pourrait être perturbant mais à la limite c'est peut-être pas si grave (bien qu'on romp le contrat de disponibilité sous 32h)
- surtout, entre la première génération et la regénération, le contenu de la procédure présentation peut avoir évolué, (ce qui gardera l'ancien export et en crééra un nouveau car la key de la présentation a changé). Ce n'est donc pas vraiment une version mise à jour du même export comme on le laisse supposer
- => 2 comportements possibles différents, en plus d'être parfois perturbants

Historiquement, j'imagine que la fonction de recréation était nécessaire car dans le dropdown on mettait le lien vers l'export créé. C'était le moyen de redemander le même (on mettait le lien car la présentation était la même !)

Maintenant j'ai l'impression que ce besoin  de génération s'estompe fortement : le dropdown a maintenant tjs un lien "statique" vers /download_exports qui soit lance la génération de l'export, soit ressert l'existant s'il n'est pas stale

Je propose de retirer cette fonctionnalité de retry, sauf pour les cas d'erreur pour lesquels elle est indispensable (bien que là aussi le procedure presentation a pu changer !)

Plus tard si on voulait vraiment re-proposer cette fonctionnalité, on pourrait faire évoluer le modèle Export, en y copiant le contenu de la présentation pour réutiliser les mêmes critères

Qu'en pensez-vous ?

2023-09-21 13:32 UTC, colinux commented
J'ai corrigé les problèmes remontés par @mfo et amélioré le wording général suite à vos retours (cf screenshot qui montre plusieurs cas possibles) : 
- Pour tous les exports (bouton "Télécharger tous les dossiers", on indique _Export de tous les dossiers_ 
- Pour export sur un onglet:  _Export de X dossiers "à suivre"_
- … sauf pour l'onglet "au total": _Export de X dossiers_ (car ils n'ont pas de statut pré-déterminé)

Il reste la discussion plus haut sur la question de regénérer un export

2023-09-28 14:15 UTC, tchak approved these changes

2023-09-28 17:26 UTC, merged