ETQ administrateur, je veux pouvoir valider des champs avec des règles simples (Regexp)
demarches-simplifiees/demarches-simplifiees.fr pull request #9535
Opened 2023-09-28 13:15 UTC by kara22

#9411

2023-10-02 07:51 UTC, colinux commented
Est-ce qu'on ne devrait pas bloquer (à la validation) les regex récursives (qui suivant les inputs peuvent bloquer les requêtes et être un petit vecteur d'attaque). Ça semble être une pratique de sécu assez répandue même si dans notre cas le risque paraît faible. Qu'en pensez-vous ?

2023-10-10 07:49 UTC, colinux commented on app/models/dossier.rb
> +    champs_public.filter(&:visible?).filter(&:expression_reguliere).map do |champ|
En passant, petites suggestions de perfs :) 


Même si c'est moins esthétique, ce serait un peu plus performant sur les grosses démarches de n'avoir qu'un seul filter au lieu de 2 consécutifs sur les mêmes éléments : 

```ruby
champs_public.filter { _1.expression_reguliere && _1.visible? }.map…
```

(J'ai aussi mis `visible?` en deuxième car, en théorie c'est l'appel le plus coûteux)

Et comme il y a un `map` juste après, (d'ailleurs j'imagine que tu n'as besoin que d'un `each` ici), auquel cas, tout pourrait être simplifié avec une seule boucle sur les champs, comme ceci par exemple, et je trouve qu'on gagne aussi en lisibilité, chaque ligne exprimant clairement son intention

```ruby
champs_public.each do |champ|
  next if champ.value.blank?
  next if !visible?
  next if champ.expression_reguliere.blank?
  next if champ.value.match?(Regexp.new(champ.expression_reguliere)

  champ.errors.add(:value, :invalid)
end
```

2023-10-10 07:51 UTC, colinux commented on app/components/editable_champ/expression_reguliere_component.rb
> +    end
un niveau d'indentation en trop pour ce end

2023-10-11 09:17 UTC, tchak commented
Comme nous sommes en Ruby 3.2, on peut utiliser la configuration "timeout" sur les expressions régulières plutôt que de gérer le timeout nous-mêmes : https://blog.kiprosh.com/ruby-3-2-0-introduce/#preventing-redos-attacks-with-regexp-timeouts

Je propose de mettre en place un timeout global (pour notre propre sécurité) relativement généreux, ainsi qu'un timeout très agressif sur les regex saisies par les administrateurs.

Le billet de blog dit aussi qu'il vaut mieux utiliser `scan` – a voir si c'est une bonne idée. De plus, on utilise la regex à trois endroits, mais on ne définit le timeout qu'à deux endroits.

2023-10-11 09:22 UTC, tchak commented
Il manque la gestion des révisions. Il faut inclure dans l'algorithme et l'UI de diff `expression_régulière`, `expression_régulière_exemple_text` et `expression_régulière_message_erreur`. Il faut aussi implémenter la logique pour déterminer si un dossier peut être rebasé - en cas de changement de `expression_régulière`, il faut vérifier que la valeur déjà saisie est toujours valide. Cela se fait dans `ProcedureRevisionChange::UpdateChamp#can_rebase?`

2023-10-11 09:47 UTC, colinux commented
Sur la perf, a priori on devrait utiliser partout `match?` (qui renvoie donc juste true/false et pas l'array des matchs). C'est encore bien plus rapide que `scan` ou `match`  ou  `=~`: 

```
Comparison:
       String#match?: 15973311.2 i/s
           String#=~:  4480361.9 i/s - 3.57x  slower
         String#scan:  1926497.3 i/s - 8.29x  slower
```

2023-10-11 09:49 UTC, colinux commented on app/models/procedure_revision.rb
> +
même remarque que mon commentaire de l'autre jour, ce serait bien de tout faire en une seule itération plutôt que passer par 4 tableaux intermédiaires assez illisibles

2023-10-11 09:51 UTC, colinux commented on app/models/type_de_champ.rb
> +    self.errors.add(:expression_reguliere, "L'expression régulière n'est pas valide synthaxiquement")
```suggestion
    self.errors.add(:expression_reguliere, "La syntaxe de l'expression régulière n'est pas valide")
```

2023-10-11 09:57 UTC, colinux reviewed
Dans l'interface admin, on pourrait préciser en hint : 

_Expression régulière ruby, essayez la sur https://rubular.com_

2023-10-11 18:32 UTC, mfo commented on app/models/champs/expression_reguliere_champ.rb
> +    regexp.match?(value)
je suis curieux, il manque pas une gestion d'erreur la dessus ?

2023-10-11 18:36 UTC, mfo commented on app/components/editable_champ/expression_reguliere_component/expression_reguliere_component.html.haml
> +- if !@champ.expression_reguliere_match?
possible d'essayer l'implem d'un validateur custom (façon `IbanValidator`). j'imagine que l'erreur popera toute seule via le systeme de validation inline des champs. hesites pas a me pinger pr pairer/identifier le chemin

2023-10-11 18:43 UTC, mfo requested changes

2023-10-11 18:43 UTC, mfo commented on app/controllers/users/dossiers_controller.rb
> +      end
les champs iban via le IbanValidator devraient permettre d'eviter ce bout de code

2023-10-11 18:43 UTC, mfo commented on app/models/type_de_champ.rb
> +    rescue Timeout::Error
dans ce begin, on veut le Regexp:TimeoutError
```suggestion
    rescue Regexp::TimeoutError 
```

je pense qu'on peut mm enlever le begin/rescue/end pour un simple rescue comme  `rescue RegexpError`

2023-10-11 18:43 UTC, mfo commented on app/models/type_de_champ.rb
> +      self.errors.add(:expression_reguliere, "Evil regex detected")
je pense ça peut se traduire comme app/components/types_de_champ_editor/champ_component/champ_component.fr.yml

2023-10-11 18:43 UTC, mfo commented on app/models/type_de_champ.rb
> +    self.errors.add(:expression_reguliere_exemple_text, "L'exemple doit correspondre à l'expression régulière fournie")
je pense ça peut se traduire comme app/components/types_de_champ_editor/champ_component/champ_component.fr.yml

2023-10-11 18:43 UTC, mfo commented on app/models/type_de_champ.rb
> +    self.errors.add(:expression_reguliere, "La syntaxe de l'expression régulière n'est pas valide")
je pense ça peut se traduire comme app/components/types_de_champ_editor/champ_component/champ_component.fr.yml

2023-10-11 18:43 UTC, mfo commented on config/locales/fr.yml
> +      evil_regexp: "L'expression régulière que vous avez entrée est potentiellement dangereuse et pourrait entraîner des problèmes de performance"
manquerait pas la trad en ?

2023-10-11 18:43 UTC, mfo commented on config/locales/models/type_de_champ/fr.yml
> +          expression_reguliere: 'Expression régulière'
manquerait pas la trad en ?

2023-10-13 08:05 UTC, mfo reviewed
j'avais oublié de publier ca

2023-10-13 10:55 UTC, kara22 commented on app/controllers/users/dossiers_controller.rb
> +      end
@mfo validator ajouté

2023-10-13 10:55 UTC, kara22 commented on app/components/editable_champ/expression_reguliere_component/expression_reguliere_component.html.haml
> +    = t('.invalid_regexp', expression_reguliere_error_message: @champ.expression_reguliere_error_message)
@mfo ajouté

2023-10-13 11:03 UTC, mfo commented on app/controllers/users/dossiers_controller.rb
> +      end
donc je pense que tu peux virer ce bout de code, le validateur devrait s'activer tout seul au dossier.save

2023-10-13 11:03 UTC, mfo commented on app/models/dossier.rb
> +  end
pareil plus besoin je pense

2023-10-13 11:05 UTC, mfo commented on app/models/type_de_champ.rb
> +  end
```suggestion

    return false  if expression_reguliere_exemple_text.match?(Regexp.new(expression_reguliere, timeout: 2.0))
        

    self.errors.add(:expression_reguliere_exemple_text, I18n.t('errors.messages.mismatch_regexp'))
    true
  rescue RegexpError
    self.errors.add(:expression_reguliere, I18n.t('errors.messages.syntax_error_regexp'))
    true
  rescue Regexp::TimeoutError
    self.errors.add(:expression_reguliere, I18n.t('errors.messages.evil_regexp'))
    true
  end
```

2023-10-16 09:40 UTC, mfo approved these changes

2023-10-17 09:22 UTC, merged