Feature ouidou/admin creation delegation administrateur pages
demarches-simplifiees/demarches-simplifiees.fr pull request #9578
Opened 2023-10-09 17:21 UTC by seb-by-ouidou

[#9111](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/issues/9111)
[ETQ super-admin, déléguer la création des comptes administrateurs à des "gestionnaires de groupe - USER STORIES](https://gitlab.adullact.net/demarches-simplifiees/evolution-du-logiciel-demarches-simplifiees/-/issues/54)

[ETQ super-admin, déléguer la création des comptes administrateurs à des "gestionnaires de groupe - LOT 3 de DEV](https://gitlab.adullact.net/demarches-simplifiees/evolution-du-logiciel-demarches-simplifiees/-/issues/57)

admin/mon-group
![Screenshot 2023-10-09 at 19-07-20 demarches-simplifiees syn](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/137039013/865343cb-9e60-4a0b-890d-902ae4eb9d88)
![Screenshot 2023-10-09 at 19-08-03 demarches-simplifiees syn](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/137039013/b718ea62-2273-44c9-8c39-5f2b4ffb8b1b)
![Screenshot 2023-10-09 at 19-08-17 demarches-simplifiees syn](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/137039013/bfdc4b6b-1101-4392-9df8-004b1b743b70)
![Screenshot 2023-10-09 at 19-08-40 demarches-simplifiees syn](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/137039013/091ebdf2-5a04-4dde-965a-4385a5811e53)

manager/administrateurs
![Screenshot 2023-10-09 at 19-09-17 Administrateurs - Tps](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/137039013/f24c46df-9d91-404b-9167-2be39de2f6b8)
![Screenshot 2023-10-09 at 19-10-05 Détails ddfasfds@fdsfds fr - Tps](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/137039013/da7eb781-5662-4a66-b1bf-4dbf30815b8d)

--------------------
> `trackingAdullactContrib`  `trackingAdullactARNiaContrib `

2023-12-14 08:36 UTC, seb-by-ouidou commented
@tchak @krichtof @colinux ready for review

2023-12-21 13:34 UTC, colinux requested changes
Hello,

quelques petits trucs mineurs, sinon c'est bon pour nous ! (review avec @krichtof )

2023-12-21 13:34 UTC, colinux commented on app/views/administrateurs/procedures/_main_menu.html.haml
On a refactorisé la navigation principale.
Le nouveau lien doit être intégré ici : https://github.com/demarches-simplifiees/demarches-simplifiees.fr/blob/main/app/views/administrateurs/_main_navigation.html.haml

2023-12-21 13:34 UTC, colinux commented on app/components/groupe_gestionnaire/card/administrateurs_component/administrateurs_component.html.haml
Maintenant que cette card est partagée entre gestionnaires et admins, le bouton "Modifier" n'est pas hyper adapté à la vue admin. Qu'est-ce que tu dirais de mettre "Voir" qui  fonctionnerait à peu près pour les 2 situations? (comme ça pas besoin de passer un param en + juste pour savoir quel libellé à afficher)

2023-12-21 13:34 UTC, colinux commented on app/components/groupe_gestionnaire/groupe_gestionnaire_administrateurs/administrateur_component.rb
> +    if is_there_at_least_another_active_admin? && @is_gestionnaire
a priori le `@is_gestionnaire`est inutile ici vu que c'est déjà conditionné dans la vue

2023-12-21 13:34 UTC, colinux commented on app/views/administrateurs/groupe_gestionnaire/gestionnaires.html.haml
> +    = #render 'add_admin_form', groupe_gestionnaire: @groupe_gestionnaire
code mort, ou pour une autre PR peut-être ?

2023-12-21 17:40 UTC, seb-by-ouidou commented
@tchak @krichtof @colinux ready for review

2023-12-22 09:06 UTC, colinux approved these changes

2023-12-22 09:16 UTC, merged