En tant qu'admin, je peux filtrer les démarches par département
demarches-simplifiees/demarches-simplifiees.fr pull request #9649
Opened 2023-10-27 08:44 UTC by krichtof

close #9642

# NE PAS MERGER

Avant de merger cette PR, il faut au préalable que https://github.com/demarches-simplifiees/demarches-simplifiees.fr/pull/9647 ait été déployée et que la tâche `BackfillDepartementServices` ait été lancée

# Ce que fait cette PR

Cette PR permet de filtrer les démarches à partir du département du service qui opère cette démarche.

![2023-10-27-103912_1245x665_scrot](https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/1111966/dd27a2b2-57bd-4485-bc8f-ae6603bb3e71)

2023-10-27 08:52 UTC, colinux approved these changes

2023-10-27 10:04 UTC, tchak commented on app/views/layouts/all.html.haml
> +                      = f.text_field :service_departement, placeholder: 'Indiquez le n° du département', class: 'fr-input'
Tu peux en faire un select, s'il te plaît ?

2023-10-27 10:04 UTC, tchak requested changes
La sélection de département doit se faire via un select.

2023-10-27 12:20 UTC, krichtof commented on app/views/layouts/all.html.haml
> +                      = f.text_field :service_departement, placeholder: 'Indiquez le n° du département', class: 'fr-input'
Yes.
J'ai rebasé le commit pour utiliser le select.

2023-10-27 13:17 UTC, tchak commented on app/views/administrateurs/procedures/all.html.haml
> +          = link_to @filter.service_departement, all_admin_procedures_path(@filter.without(:service_departement)), class: 'fr-tag fr-tag--dismiss fr-mb-1w'
```suggestion
          = link_to "#{@filter.service_departement} – #{APIGeoService.departement_name(@filter.service_departement)}", all_admin_procedures_path(@filter.without(:service_departement)), class: 'fr-tag fr-tag--dismiss fr-mb-1w'
```

2023-10-27 15:47 UTC, tchak approved these changes

2023-10-30 09:25 UTC, merged

2023-10-30 21:32 UTC, colinux commented
@krichtof est ce que ce serait pas une bonne idée de commenter rapidement dans les releases concernées ce qu'il faut faire avant que les instances déploient ça?