ETQ Admin, je veux un sommaire qui me pernet de naviguer de section en section
demarches-simplifiees/demarches-simplifiees.fr pull request #9894
Opened 2024-01-04 15:36 UTC by lisa-durand

closes #9794

<img width="1248" alt="Capture d’écran 2024-01-04 à 16 10 00" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/6756627/91b919db-c2fc-47ed-a0b9-6bd674d4a23b">

2024-01-08 10:15 UTC, mfo requested changes
ptis commentaire pour les spacers, il y a le prob des annotations privées.

PS: ca ne prends pas en compte les titres de sections des blocs répétable. p-e ds une v2 ?

2024-01-08 10:15 UTC, mfo commented on app/components/conditions/champs_conditions_component/champs_conditions_component.html.haml
> +    .conditionnel.mt-2
se sont d'anciens spacers les `mt-x`. Se serait top d'utiliser ceux du dsfr, qu'en penses tu ?
```suggestion
    .conditionnel.fr-mt-2v
```

2024-01-08 10:15 UTC, mfo commented on app/components/conditions/champs_conditions_component/champs_conditions_component.html.haml
> +        %table.condition-table.mt-2
```suggestion
        %table.condition-table.fr-mt-2v
```

2024-01-08 10:15 UTC, mfo commented on app/views/administrateurs/procedures/champs.html.haml
> +      = render TypesDeChampEditor::EditorComponent.new(revision: @procedure.draft_revision)
il faudrait faire pareil sur les annotations car ça casse le layout qui passe en full screen : 
<img width="1710" alt="Screenshot 2024-01-08 at 11 12 11 AM" src="https://github.com/demarches-simplifiees/demarches-simplifiees.fr/assets/125964/5e3a0ad6-04eb-4c9e-87c2-8ed7fa7d17c7">

2024-01-08 10:34 UTC, colinux reviewed
Génial. Une remarque pour les niveaux 4 et +. On pourra voir ce que ça donne sur les grosses démarches type fonds verts avec 30 titres ou plus.

Je serais encore plus satisfait avec  : 

```css
.type-de-champ {
  scroll-margin: 0.5em;
}
```

(dans `app/assets/stylesheets/procedure_champs_editor.scss`), pour pas que le background du tdc "colle" en haut à la fenêtre (et aussi car c'est [ma réponse la plus upvotée sur stackoverflow](https://stackoverflow.com/questions/49859042/scrollintoview-with-margin/59611245#59611245))

J'espère que le fait de perdre toute la largeur pour l'éditeur ne fera pas trop débat (dommage qu'on puisse pas replier cette sidebar comme les menus sur mobile).  Ça peut être aussi un peu perturbant lors de l'ajout du premier titre, mais ça ne me paraît pas  suffisamment génant non plus.

2024-01-08 10:34 UTC, colinux commented on app/views/administrateurs/procedures/_champs_summary.html.haml
> +              %a.fr-sidemenu__link{ class: level == 3 ? 'custom-link-grey': '', href: "##{dom_id(header, :type_de_champ_editor)}" }= "-- #{header.libelle}"
Est-ce qu'il ne devrait pas y avoir du gris aussi pour les levels 4 et +  ?

2024-01-08 13:24 UTC, lisa-durand commented on app/components/conditions/champs_conditions_component/champs_conditions_component.html.haml
> +    .conditionnel.mt-2
en regardant dans le code - il y a pas mal de references encore du `.mt-2` et d'autres anciennes espaces - du coup je me demande si ça vaut pas le coup de faire une passe spécifiquement la-dessus ?

2024-01-08 13:24 UTC, lisa-durand commented on app/views/administrateurs/procedures/_champs_summary.html.haml
> +              %a.fr-sidemenu__link{ class: level == 3 ? 'custom-link-grey': '', href: "##{dom_id(header, :type_de_champ_editor)}" }= "-- #{header.libelle}"
ah je n'avais pas fait attention qu'il pouvait y avoir d'autres niveaux de titre - je vais changer ça. Vous avez une idée des stats sur les niveaux de titres utilisés ?

2024-01-08 13:26 UTC, lisa-durand commented
> c'est top ! juste les ptis commentaires pour les spacers et le prob des annotations privées.
> 
> PS: ca ne prends pas en compte les titres de sections des blocs répétable. p-e ds une v2 ? PPS: il y avait une créa d'Olivier sur un sommaire (mais côté) usager. Ça vaudrait p-e le coup d'utiliser le mm design ETQ admin/ETQ usager. https://github.com/orgs/demarches-simplifiees/projects/1/views/1?filterQuery=sommaire&pane=issue&itemId=27834718

Pour le design, j'ai du faire un mix entre le side menu et le sommaire du DSFR car rien ne correspondait totalement à nos besoins. Dans les maquettes d'Olivier par exemple c'est le sommaire, et il n'y a pas de hiérarchie entre les différents niveaux de titre et on n'a pas le droit de le mettre en fix.

2024-01-08 13:38 UTC, lisa-durand commented
> Génial. Une remarque pour les niveaux 4 et +. On pourra voir ce que ça donne sur les grosses démarches type fonds verts avec 30 titres ou plus.
> 
> Je serais encore plus satisfait avec :
> 
> ```css
> .type-de-champ {
>   scroll-margin: 0.5em;
> }
> ```
> 
> (dans `app/assets/stylesheets/procedure_champs_editor.scss`), pour pas que le background du tdc "colle" en haut à la fenêtre (et aussi car c'est [ma réponse la plus upvotée sur stackoverflow](https://stackoverflow.com/questions/49859042/scrollintoview-with-margin/59611245#59611245))
> 
> J'espère que le fait de perdre toute la largeur pour l'éditeur ne fera pas trop débat (dommage qu'on puisse pas replier cette sidebar comme les menus sur mobile). Ça peut être aussi un peu perturbant lors de l'ajout du premier titre, mais ça ne me paraît pas suffisamment génant non plus.

je connaissais pas ce petit css tips ! La classe pour les upvotes Stackoverflow 😎

2024-01-08 16:47 UTC, colinux commented on app/views/administrateurs/procedures/_champs_summary.html.haml
> +              %a.fr-sidemenu__link{ class: level == 3 ? 'custom-link-grey': '', href: "##{dom_id(header, :type_de_champ_editor)}" }= "-- #{header.libelle}"
aucune idée, mais j'ai déjà croisé quelques fois des niveau 4. Idée d'évolution possible si pour certaines démarches le menu devenait trop long: se limiter aux 3 premiers niveaux, et/ou utiliser le système de closure de ce composant pour "replier" les niveaux  3+.

2024-01-11 07:48 UTC, mfo commented on app/components/conditions/champs_conditions_component/champs_conditions_component.html.haml
> +    .conditionnel.mt-2
je pense pas que ça necessite d'aller nettoyer toute la codebase, on peut faire ça en mode opportuniste et eviter d'en ajouter d'autres

2024-01-11 08:39 UTC, mfo approved these changes

2024-01-16 10:46 UTC, merged